<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            array('phone' => '93',   'code' => 'AF', 'name' => 'Afghanistan',                   'currency' => 'AFN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '355',  'code' => 'AL', 'name' => 'Albania',                       'currency' => 'ALL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '213',  'code' => 'DZ', 'name' => 'Algeria',                       'currency' => 'DZD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '376',  'code' => 'AD', 'name' => 'Andorra',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '244',  'code' => 'AO', 'name' => 'Angola',                        'currency' => 'AOA', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-268','code' => 'AG', 'name' => 'Antigua and Barbuda',           'currency' => 'XCD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '54',   'code' => 'AR', 'name' => 'Argentina',                     'currency' => 'ARS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '374',  'code' => 'AM', 'name' => 'Armenia',                       'currency' => 'AMD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '61',   'code' => 'AU', 'name' => 'Australia',                     'currency' => 'AUD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '43',   'code' => 'AT', 'name' => 'Austria',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '994',  'code' => 'AZ', 'name' => 'Azerbaijan',                    'currency' => 'AZN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-242','code' => 'BS', 'name' => 'Bahamas',                       'currency' => 'BSD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '973',  'code' => 'BH', 'name' => 'Bahrain',                       'currency' => 'BHD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '880',  'code' => 'BD', 'name' => 'Bangladesh',                    'currency' => 'BDT', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-246','code' => 'BB', 'name' => 'Barbados',                      'currency' => 'BBD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '375',  'code' => 'BY', 'name' => 'Belarus',                       'currency' => 'BYN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '32',   'code' => 'BE', 'name' => 'Belgium',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '501',  'code' => 'BZ', 'name' => 'Belize',                        'currency' => 'BZD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '229',  'code' => 'BJ', 'name' => 'Benin',                         'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '975',  'code' => 'BT', 'name' => 'Bhutan',                        'currency' => 'BTN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '591',  'code' => 'BO', 'name' => 'Bolivia',                       'currency' => 'BOB', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '387',  'code' => 'BA', 'name' => 'Bosnia and Herzegovina',        'currency' => 'BAM', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '267',  'code' => 'BW', 'name' => 'Botswana',                      'currency' => 'BWP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '55',   'code' => 'BR', 'name' => 'Brazil',                        'currency' => 'BRL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '673',  'code' => 'BN', 'name' => 'Brunei Darussalam',             'currency' => 'BND', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '359',  'code' => 'BG', 'name' => 'Bulgaria',                      'currency' => 'BGN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '226',  'code' => 'BF', 'name' => 'Burkina Faso',                  'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '257',  'code' => 'BI', 'name' => 'Burundi',                       'currency' => 'BIF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '855',  'code' => 'KH', 'name' => 'Cambodia',                      'currency' => 'KHR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '237',  'code' => 'CM', 'name' => 'Cameroon',                      'currency' => 'XAF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1',    'code' => 'CA', 'name' => 'Canada',                        'currency' => 'CAD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '238',  'code' => 'CV', 'name' => 'Cape Verde',                    'currency' => 'CVE', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '236',  'code' => 'CF', 'name' => 'Central African Republic',      'currency' => 'XAF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '235',  'code' => 'TD', 'name' => 'Chad',                          'currency' => 'XAF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '56',   'code' => 'CL', 'name' => 'Chile',                         'currency' => 'CLP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '86',   'code' => 'CN', 'name' => 'China',                         'currency' => 'CNY', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '57',   'code' => 'CO', 'name' => 'Colombia',                      'currency' => 'COP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '269',  'code' => 'KM', 'name' => 'Comoros',                       'currency' => 'KMF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '242',  'code' => 'CG', 'name' => 'Congo',                         'currency' => 'XAF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '243',  'code' => 'CD', 'name' => 'Congo, Dem. Rep.',              'currency' => 'CDF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '506',  'code' => 'CR', 'name' => 'Costa Rica',                    'currency' => 'CRC', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '385',  'code' => 'HR', 'name' => 'Croatia',                       'currency' => 'HRK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '53',   'code' => 'CU', 'name' => 'Cuba',                          'currency' => 'CUP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '357',  'code' => 'CY', 'name' => 'Cyprus',                        'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '420',  'code' => 'CZ', 'name' => 'Czech Republic',                'currency' => 'CZK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '45',   'code' => 'DK', 'name' => 'Denmark',                       'currency' => 'DKK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '253',  'code' => 'DJ', 'name' => 'Djibouti',                      'currency' => 'DJF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-767','code' => 'DM', 'name' => 'Dominica',                      'currency' => 'XCD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-809','code' => 'DO', 'name' => 'Dominican Republic',            'currency' => 'DOP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '593',  'code' => 'EC', 'name' => 'Ecuador',                       'currency' => 'USD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '20',   'code' => 'EG', 'name' => 'Egypt',                         'currency' => 'EGP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '503',  'code' => 'SV', 'name' => 'El Salvador',                   'currency' => 'USD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '240',  'code' => 'GQ', 'name' => 'Equatorial Guinea',             'currency' => 'XAF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '291',  'code' => 'ER', 'name' => 'Eritrea',                       'currency' => 'ERN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '372',  'code' => 'EE', 'name' => 'Estonia',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '251',  'code' => 'ET', 'name' => 'Ethiopia',                      'currency' => 'ETB', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '679',  'code' => 'FJ', 'name' => 'Fiji',                          'currency' => 'FJD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '358',  'code' => 'FI', 'name' => 'Finland',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '33',   'code' => 'FR', 'name' => 'France',                        'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '241',  'code' => 'GA', 'name' => 'Gabon',                         'currency' => 'XAF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '220',  'code' => 'GM', 'name' => 'Gambia',                        'currency' => 'GMD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '995',  'code' => 'GE', 'name' => 'Georgia',                       'currency' => 'GEL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '49',   'code' => 'DE', 'name' => 'Germany',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '233',  'code' => 'GH', 'name' => 'Ghana',                         'currency' => 'GHS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '30',   'code' => 'GR', 'name' => 'Greece',                        'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-473','code' => 'GD', 'name' => 'Grenada',                       'currency' => 'XCD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '502',  'code' => 'GT', 'name' => 'Guatemala',                     'currency' => 'GTQ', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '224',  'code' => 'GN', 'name' => 'Guinea',                        'currency' => 'GNF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '245',  'code' => 'GW', 'name' => 'Guinea-Bissau',                 'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '592',  'code' => 'GY', 'name' => 'Guyana',                        'currency' => 'GYD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '509',  'code' => 'HT', 'name' => 'Haiti',                         'currency' => 'HTG', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '504',  'code' => 'HN', 'name' => 'Honduras',                      'currency' => 'HNL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '852',  'code' => 'HK', 'name' => 'Hong Kong',                     'currency' => 'HKD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '36',   'code' => 'HU', 'name' => 'Hungary',                       'currency' => 'HUF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '354',  'code' => 'IS', 'name' => 'Iceland',                       'currency' => 'ISK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '91',   'code' => 'IN', 'name' => 'India',                         'currency' => 'INR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '62',   'code' => 'ID', 'name' => 'Indonesia',                     'currency' => 'IDR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '98',   'code' => 'IR', 'name' => 'Iran',                          'currency' => 'IRR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '964',  'code' => 'IQ', 'name' => 'Iraq',                          'currency' => 'IQD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '353',  'code' => 'IE', 'name' => 'Ireland',                       'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '39',   'code' => 'IT', 'name' => 'Italy',                         'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-876','code' => 'JM', 'name' => 'Jamaica',                       'currency' => 'JMD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '81',   'code' => 'JP', 'name' => 'Japan',                         'currency' => 'JPY', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '962',  'code' => 'JO', 'name' => 'Jordan',                        'currency' => 'JOD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '7',    'code' => 'KZ', 'name' => 'Kazakhstan',                    'currency' => 'KZT', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '254',  'code' => 'KE', 'name' => 'Kenya',                         'currency' => 'KES', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '686',  'code' => 'KI', 'name' => 'Kiribati',                      'currency' => 'AUD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '850',  'code' => 'KP', 'name' => 'Korea, North',                  'currency' => 'KPW', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '82',   'code' => 'KR', 'name' => 'Korea, South',                  'currency' => 'KRW', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '965',  'code' => 'KW', 'name' => 'Kuwait',                        'currency' => 'KWD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '996',  'code' => 'KG', 'name' => 'Kyrgyzstan',                    'currency' => 'KGS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '856',  'code' => 'LA', 'name' => 'Lao PDR',                       'currency' => 'LAK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '371',  'code' => 'LV', 'name' => 'Latvia',                        'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '961',  'code' => 'LB', 'name' => 'Lebanon',                       'currency' => 'LBP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '266',  'code' => 'LS', 'name' => 'Lesotho',                       'currency' => 'LSL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '231',  'code' => 'LR', 'name' => 'Liberia',                       'currency' => 'LRD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '218',  'code' => 'LY', 'name' => 'Libya',                         'currency' => 'LYD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '423',  'code' => 'LI', 'name' => 'Liechtenstein',                 'currency' => 'CHF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '370',  'code' => 'LT', 'name' => 'Lithuania',                     'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '352',  'code' => 'LU', 'name' => 'Luxembourg',                    'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '853',  'code' => 'MO', 'name' => 'Macao',                         'currency' => 'MOP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '389',  'code' => 'MK', 'name' => 'Macedonia, FYR',                'currency' => 'MKD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '261',  'code' => 'MG', 'name' => 'Madagascar',                    'currency' => 'MGA', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '265',  'code' => 'MW', 'name' => 'Malawi',                        'currency' => 'MWK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '60',   'code' => 'MY', 'name' => 'Malaysia',                      'currency' => 'MYR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '960',  'code' => 'MV', 'name' => 'Maldives',                      'currency' => 'MVR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '223',  'code' => 'ML', 'name' => 'Mali',                          'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '356',  'code' => 'MT', 'name' => 'Malta',                         'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '692',  'code' => 'MH', 'name' => 'Marshall Islands',              'currency' => 'USD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '222',  'code' => 'MR', 'name' => 'Mauritania',                    'currency' => 'MRU', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '230',  'code' => 'MU', 'name' => 'Mauritius',                     'currency' => 'MUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '52',   'code' => 'MX', 'name' => 'Mexico',                        'currency' => 'MXN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '691',  'code' => 'FM', 'name' => 'Micronesia, Fed. Sts.',         'currency' => 'USD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '373',  'code' => 'MD', 'name' => 'Moldova',                       'currency' => 'MDL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '377',  'code' => 'MC', 'name' => 'Monaco',                        'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '976',  'code' => 'MN', 'name' => 'Mongolia',                      'currency' => 'MNT', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '382',  'code' => 'ME', 'name' => 'Montenegro',                    'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '212',  'code' => 'MA', 'name' => 'Morocco',                       'currency' => 'MAD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '258',  'code' => 'MZ', 'name' => 'Mozambique',                    'currency' => 'MZN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '264',  'code' => 'NA', 'name' => 'Namibia',                       'currency' => 'NAD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '674',  'code' => 'NR', 'name' => 'Nauru',                         'currency' => 'AUD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '977',  'code' => 'NP', 'name' => 'Nepal',                         'currency' => 'NPR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '31',   'code' => 'NL', 'name' => 'Netherlands',                   'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '64',   'code' => 'NZ', 'name' => 'New Zealand',                   'currency' => 'NZD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '505',  'code' => 'NI', 'name' => 'Nicaragua',                     'currency' => 'NIO', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '227',  'code' => 'NE', 'name' => 'Niger',                         'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '234',  'code' => 'NG', 'name' => 'Nigeria',                       'currency' => 'NGN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '47',   'code' => 'NO', 'name' => 'Norway',                        'currency' => 'NOK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '968',  'code' => 'OM', 'name' => 'Oman',                          'currency' => 'OMR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '92',   'code' => 'PK', 'name' => 'Pakistan',                      'currency' => 'PKR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '680',  'code' => 'PW', 'name' => 'Palau',                         'currency' => 'USD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '970',  'code' => 'PS', 'name' => 'Palestine',                     'currency' => 'ILS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '507',  'code' => 'PA', 'name' => 'Panama',                        'currency' => 'PAB', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '675',  'code' => 'PG', 'name' => 'Papua New Guinea',              'currency' => 'PGK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '595',  'code' => 'PY', 'name' => 'Paraguay',                      'currency' => 'PYG', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '51',   'code' => 'PE', 'name' => 'Peru',                          'currency' => 'PEN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '63',   'code' => 'PH', 'name' => 'Philippines',                   'currency' => 'PHP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '48',   'code' => 'PL', 'name' => 'Poland',                        'currency' => 'PLN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '351',  'code' => 'PT', 'name' => 'Portugal',                      'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '974',  'code' => 'QA', 'name' => 'Qatar',                         'currency' => 'QAR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '40',   'code' => 'RO', 'name' => 'Romania',                       'currency' => 'RON', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '7',    'code' => 'RU', 'name' => 'Russian Federation',            'currency' => 'RUB', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '250',  'code' => 'RW', 'name' => 'Rwanda',                        'currency' => 'RWF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-869','code' => 'KN', 'name' => 'Saint Kitts and Nevis',         'currency' => 'XCD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-758','code' => 'LC', 'name' => 'Saint Lucia',                   'currency' => 'XCD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-784','code' => 'VC', 'name' => 'Saint Vincent & Grenadines',    'currency' => 'XCD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '685',  'code' => 'WS', 'name' => 'Samoa',                         'currency' => 'WST', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '378',  'code' => 'SM', 'name' => 'San Marino',                    'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '239',  'code' => 'ST', 'name' => 'Sao Tome and Principe',         'currency' => 'STN', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '966',  'code' => 'SA', 'name' => 'Saudi Arabia',                  'currency' => 'SAR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '221',  'code' => 'SN', 'name' => 'Senegal',                       'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '381',  'code' => 'RS', 'name' => 'Serbia',                        'currency' => 'RSD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '248',  'code' => 'SC', 'name' => 'Seychelles',                    'currency' => 'SCR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '232',  'code' => 'SL', 'name' => 'Sierra Leone',                  'currency' => 'SLL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '65',   'code' => 'SG', 'name' => 'Singapore',                     'currency' => 'SGD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '421',  'code' => 'SK', 'name' => 'Slovakia',                      'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '386',  'code' => 'SI', 'name' => 'Slovenia',                      'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '677',  'code' => 'SB', 'name' => 'Solomon Islands',               'currency' => 'SBD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '252',  'code' => 'SO', 'name' => 'Somalia',                       'currency' => 'SOS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '27',   'code' => 'ZA', 'name' => 'South Africa',                  'currency' => 'ZAR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '211',  'code' => 'SS', 'name' => 'South Sudan',                   'currency' => 'SSP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '34',   'code' => 'ES', 'name' => 'Spain',                         'currency' => 'EUR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '94',   'code' => 'LK', 'name' => 'Sri Lanka',                     'currency' => 'LKR', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '249',  'code' => 'SD', 'name' => 'Sudan',                         'currency' => 'SDG', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '597',  'code' => 'SR', 'name' => 'Suriname',                      'currency' => 'SRD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '268',  'code' => 'SZ', 'name' => 'Swaziland',                     'currency' => 'SZL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '46',   'code' => 'SE', 'name' => 'Sweden',                        'currency' => 'SEK', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '41',   'code' => 'CH', 'name' => 'Switzerland',                   'currency' => 'CHF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '963',  'code' => 'SY', 'name' => 'Syrian Arab Republic',          'currency' => 'SYP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '886',  'code' => 'TW', 'name' => 'Taiwan',                        'currency' => 'TWD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '992',  'code' => 'TJ', 'name' => 'Tajikistan',                    'currency' => 'TJS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '255',  'code' => 'TZ', 'name' => 'Tanzania',                      'currency' => 'TZS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '66',   'code' => 'TH', 'name' => 'Thailand',                      'currency' => 'THB', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '228',  'code' => 'TG', 'name' => 'Togo',                          'currency' => 'XOF', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '676',  'code' => 'TO', 'name' => 'Tonga',                         'currency' => 'TOP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1-868','code' => 'TT', 'name' => 'Trinidad and Tobago',           'currency' => 'TTD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '216',  'code' => 'TN', 'name' => 'Tunisia',                       'currency' => 'TND', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '90',   'code' => 'TR', 'name' => 'Turkey',                        'currency' => 'TRY', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '993',  'code' => 'TM', 'name' => 'Turkmenistan',                  'currency' => 'TMT', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '688',  'code' => 'TV', 'name' => 'Tuvalu',                        'currency' => 'AUD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '256',  'code' => 'UG', 'name' => 'Uganda',                        'currency' => 'UGX', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '380',  'code' => 'UA', 'name' => 'Ukraine',                       'currency' => 'UAH', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '971',  'code' => 'AE', 'name' => 'United Arab Emirates',          'currency' => 'AED', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '44',   'code' => 'GB', 'name' => 'United Kingdom',                'currency' => 'GBP', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '1',    'code' => 'US', 'name' => 'United States',                 'currency' => 'USD', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '598',  'code' => 'UY', 'name' => 'Uruguay',                       'currency' => 'UYU', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '998',  'code' => 'UZ', 'name' => 'Uzbekistan',                    'currency' => 'UZS', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '678',  'code' => 'VU', 'name' => 'Vanuatu',                       'currency' => 'VUV', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '58',   'code' => 'VE', 'name' => 'Venezuela',                     'currency' => 'VES', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '84',   'code' => 'VN', 'name' => 'Viet Nam',                      'currency' => 'VND', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '967',  'code' => 'YE', 'name' => 'Yemen',                         'currency' => 'YER', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '260',  'code' => 'ZM', 'name' => 'Zambia',                        'currency' => 'ZMW', 'publish' => '1', 'created_at' => now(), 'updated_at' => now()),
            array('phone' => '263',  'code' => 'ZW', 'name' => 'Zimbabwe',                      'currency' => 'ZWL', 'publish' => '1', 'created_at' => now(), 'updated_at' => now())
        ];

        foreach ($data as $row) {
            \App\Models\Country::create($row);
        }
    }
}
