FROM php:8.2.7-fpm

# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    libpq-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_pgsql

# Download composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# # Install composer
# RUN composer install --ignore-platform-reqs

# Delete vendor directory
RUN rm -rf /var/www/html/vendor


# Install dependencies without optimization
RUN composer install --no-dev


# Copy existing application directory permissions
COPY --chown=www-data:www-data . /var/www

# Laravel Comands
RUN php artisan storage:link
RUN php artisan key:generate

# Set files and folders permissions
RUN find * -type d -print0 | xargs -0 chmod 0755
RUN find . -type f -print0 | xargs -0 chmod 0644 
RUN chown -R www-data:www-data .

# Change current user to root
USER root

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]